name: grooming-pipeline-analysis-3e3f790d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.*
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - tifffile>=2021.7.0
  - imageio>=2.19.0
  - scikit-image>=0.18.0
  - scikit-learn>=1.0.0
  - statsmodels>=0.13.0
  - pytest>=7.0.0
  - pytest-cov>=3.0.0
  - black>=23.0.0
  - ruff>=0.1.0
  - tqdm>=4.62.0
  - pip:
    - click>=8.0.0
